# Generated by Django 5.2 on 2025-04-18 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_teacher_student_alter_student_class_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='student',
        ),
    ]
